version: '3.4'
services:
  redis:
    image: redis:6.0
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "16379:6379"
    volumes:
      - ./data/redis:/var/lib/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf